<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

$app = Factory::getContainer()->get(Joomla\CMS\Application\SiteApplication::class);

// Create a shortcut for params.
$params  = &$this->item->params;
$canEdit = $this->item->params->get('access-edit');
$info    = $this->item->params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate       = Factory::getDate()->format(Text::_('DATE_FORMAT_LC6'));
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isUnpublished     = $this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;
?>

<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>

<div class="item-content">
    <?php if ($isUnpublished) { ?>
        <div class="system-unpublished">
        <?php
    }

    echo LayoutHelper::render('joomla.content.blog_style_default_item_title', $this->item);

    if ($canEdit) {
        echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item));
    }

    // Content is generated by content plugin event "onContentAfterTitle"
    echo $this->item->event->afterDisplayTitle;

    // @todo Not that elegant would be nice to group the params
    $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date')
        || $params->get('show_create_date') || $params->get('show_hits')
        || $params->get('show_category') || $params->get('show_parent_category')
        || $params->get('show_author') || $assocParam);

    if ($useDefList && ($info == 0 || $info == 2)) {
        echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
    }
    if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
        echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
    }

    // Content is generated by content plugin event "onContentBeforeDisplay"
    echo $this->item->event->beforeDisplayContent;

    echo $this->item->introtext;

    if ($useDefList && $info == 1) {
        echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));
    }

    if (($info == 1 || $info == 2) && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
        echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags);
    }

    if ($params->get('show_readmore') && $this->item->readmore) {
        if ($params->get('access-view')) {
            $link = Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
        } else {
            $menu = $app->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
        }
        echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link));
    }

    if ($isUnpublished) {
        ?>
        </div>
    <?php } ?>

</div>

<?php // Content is generated by content plugin event "onContentAfterDisplay"
?>
<?php echo $this->item->event->afterDisplayContent; ?>
