<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

\defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

$app = Factory::getContainer()->get(Joomla\CMS\Application\SiteApplication::class);

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = $app->getIdentity();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = Associations::isEnabled() && $params->get('show_associations');
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
$accessView        = $params->get('access-view');
?>
<article class="uk-article item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? $app->get('language') : $this->item->language; ?>">

    <?php if ($this->params->get('show_page_heading')) { ?>
    <h1 class="uk-h1 uk-margin-remove-top uk-margin-medium-bottom page-header"><?php echo $this->escape($this->params->get('page_heading')); ?></h1>
    <?php }

    if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    }

    $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date')
        || $params->get('show_create_date') || $params->get('show_hits')
        || $params->get('show_category') || $params->get('show_parent_category')
        || $params->get('show_author') || $assocParam;

    if ($params->get('show_title')) {
        echo '<' . $htag . ' class="uk-article-title uk-margin-remove-top uk-margin-medium-bottom" itemprop="headline">';
        echo $this->escape($this->item->title);
        echo '</' . $htag . '>';

        $badges = '';
        if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) {
            $badges .= '<span class="uk-label uk-label-warning uk-margin-small-right uk-text-uppercase">' . Text::_('JUNPUBLISHED') . '</span>';
        }
        if ($isNotPublishedYet) {
            $badges .= '<span class="uk-label uk-label-warning uk-margin-small-right uk-text-uppercase">' . Text::_('JNOTPUBLISHEDYET') . '</span>';
        }
        if ($isExpired) {
            $badges .= '<span class="uk-label uk-label-warning uk-margin-small-right uk-text-uppercase">' . Text::_('JEXPIRED') . '</span>';
        }
        if ($badges) {
            echo '<div class="uk-flex uk-margin">' . $badges . '</div>';
        }
    }

    if ($accessView) {
        echo LayoutHelper::render('joomla.content.full_image', $this->item);
    }

    if ($canEdit) {
        echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item));
    }

    // Content is generated by content plugin event "onContentAfterTitle"
    echo $this->item->event->afterDisplayTitle;

    // Content is generated by content plugin event "onContentBeforeDisplay"
    echo $this->item->event->beforeDisplayContent;

    if ($useDefList && ($info == 0 || $info == 2)) {
        echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above'));
    }

    if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
        $this->item->tagLayout = new FileLayout('joomla.content.tags');
        echo $this->item->tagLayout->render($this->item->tags->itemTags);
    }

    if ((int) $params->get('urls_position', 0) === 0) {
        echo $this->loadTemplate('links');
    }

    if ($accessView) {
        if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) {
            echo $this->item->pagination;
        }
        if (isset($this->item->toc)) {
            echo $this->item->toc;
        }

        echo '<div itemprop="articleBody" class="uk-article-body">' . $this->item->text . '</div>';

        if ($useDefList && $info == 1) {
            echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below'));
        }

        if (($info == 1 || $info == 2) && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
            if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) {
                $this->item->tagLayout = new FileLayout('joomla.content.tags');
                echo $this->item->tagLayout->render($this->item->tags->itemTags);
            }
        }

        if ((int) $params->get('urls_position', 0) === 1) {
            echo $this->loadTemplate('links');
        }

        if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) {
            echo $this->item->pagination;
        }

    // Optional teaser intro text for guests
    } elseif ($params->get('show_noauth') == true && $user->get('guest')) {
        echo LayoutHelper::render('joomla.content.intro_image', $this->item);
        echo HTMLHelper::_('content.prepare', $this->item->introtext);

        // Optional link to let them register to see the whole article.
        if ($params->get('show_readmore') && $this->item->fulltext != null) {
            $menu = $app->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
            echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link));
        }
    }

    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    }

    // Content is generated by content plugin event "onContentAfterDisplay"
    echo $this->item->event->afterDisplayContent;

    ?>
</article>
